[2025-01-27T15:06:27.461+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_pipeline_intraday.start_producer_intraday manual__2025-01-27T15:06:23.375284+00:00 [queued]>
[2025-01-27T15:06:27.467+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_pipeline_intraday.start_producer_intraday manual__2025-01-27T15:06:23.375284+00:00 [queued]>
[2025-01-27T15:06:27.467+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-27T15:06:27.485+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): start_producer_intraday> on 2025-01-27 15:06:23.375284+00:00
[2025-01-27T15:06:27.489+0000] {standard_task_runner.py:57} INFO - Started process 57 to run task
[2025-01-27T15:06:27.492+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'stock_price_pipeline_intraday', 'start_producer_intraday', 'manual__2025-01-27T15:06:23.375284+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/stock_pipeline_dag.py', '--cfg-path', '/tmp/tmpz7botwhc']
[2025-01-27T15:06:27.493+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask start_producer_intraday
[2025-01-27T15:06:27.550+0000] {task_command.py:415} INFO - Running <TaskInstance: stock_price_pipeline_intraday.start_producer_intraday manual__2025-01-27T15:06:23.375284+00:00 [running]> on host 3297853633a2
[2025-01-27T15:06:28.116+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_price_pipeline_intraday' AIRFLOW_CTX_TASK_ID='start_producer_intraday' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T15:06:23.375284+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T15:06:23.375284+00:00'
[2025-01-27T15:06:28.118+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-27T15:06:28.118+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec producer-5min python /opt/airflow/dags/producers/kafka_producer_5min.py']
[2025-01-27T15:06:28.127+0000] {subprocess.py:86} INFO - Output:
[2025-01-27T15:06:28.479+0000] {subprocess.py:93} INFO - python: can't open file '/opt/airflow/dags/producers/kafka_producer_5min.py': [Errno 2] No such file or directory
[2025-01-27T15:06:28.490+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-01-27T15:06:28.499+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-01-27T15:06:28.502+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_pipeline_intraday, task_id=start_producer_intraday, execution_date=20250127T150623, start_date=20250127T150627, end_date=20250127T150628
[2025-01-27T15:06:28.516+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task start_producer_intraday (Bash command failed. The command returned a non-zero exit code 2.; 57)
[2025-01-27T15:06:28.536+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-27T15:06:28.555+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
