[2025-01-28T08:44:43.112+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_pipeline_intraday.start_producer_intraday manual__2025-01-28T08:44:36.809842+00:00 [queued]>
[2025-01-28T08:44:43.124+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_pipeline_intraday.start_producer_intraday manual__2025-01-28T08:44:36.809842+00:00 [queued]>
[2025-01-28T08:44:43.125+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-28T08:44:43.153+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): start_producer_intraday> on 2025-01-28 08:44:36.809842+00:00
[2025-01-28T08:44:43.160+0000] {standard_task_runner.py:57} INFO - Started process 63 to run task
[2025-01-28T08:44:43.165+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'stock_price_pipeline_intraday', 'start_producer_intraday', 'manual__2025-01-28T08:44:36.809842+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/stock_pipeline_dag.py', '--cfg-path', '/tmp/tmpbjb9zpd3']
[2025-01-28T08:44:43.171+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask start_producer_intraday
[2025-01-28T08:44:43.343+0000] {task_command.py:415} INFO - Running <TaskInstance: stock_price_pipeline_intraday.start_producer_intraday manual__2025-01-28T08:44:36.809842+00:00 [running]> on host 5daa95ef0080
[2025-01-28T08:44:44.374+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_price_pipeline_intraday' AIRFLOW_CTX_TASK_ID='start_producer_intraday' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T08:44:36.809842+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T08:44:36.809842+00:00'
[2025-01-28T08:44:44.376+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-28T08:44:44.376+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec producer-5min python /opt/airflow/dags/producers/intraday/kafka_producer_5min.py']
[2025-01-28T08:44:44.388+0000] {subprocess.py:86} INFO - Output:
[2025-01-28T08:44:44.650+0000] {subprocess.py:93} INFO - python: can't open file '/opt/airflow/dags/producers/intraday/kafka_producer_5min.py': [Errno 2] No such file or directory
[2025-01-28T08:44:44.664+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-01-28T08:44:44.675+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-01-28T08:44:44.680+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_pipeline_intraday, task_id=start_producer_intraday, execution_date=20250128T084436, start_date=20250128T084443, end_date=20250128T084444
[2025-01-28T08:44:44.697+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task start_producer_intraday (Bash command failed. The command returned a non-zero exit code 2.; 63)
[2025-01-28T08:44:44.739+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-28T08:44:44.765+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
